In [2]:
#1.create and reshape array
import numpy as np

In [6]:
arr=np.arange(1,21)

In [7]:
matrix=arr.reshape(4,5)

In [8]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
matrix.shape

(4, 5)

In [10]:
matrix.ndim

2

In [28]:
#2.array statistics
marks=np.array([15,25,35,45,55,65,75,85,95,105])
mean=np.mean(marks)
median=np.median(marks)
maximum=np.max(marks)
minimum=np.min(marks)

In [23]:
print("mean:",mean)

mean: 60.0


In [25]:
print("median:",median)

median: 60.0


In [27]:
print("maximum:",maximum)

maximum: 105


In [29]:
print("minimum:",minimum)

minimum: 15


In [30]:
#3.matrix operations
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [31]:
print("addition:")
print(a+b)

addition:
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [32]:
print("substracion")
print(a-b)

substracion
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [33]:
print("element-wise multiplication:")
print(a*b)

element-wise multiplication:
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [34]:
#4.real world sale analysis
sales=np.array([12000,15000,18000,14000,22000,25000,21000,19000,28000,30000,27000,32000])

In [36]:
total_sales=np.sum(sales)
average_sales=np.mean(sales)
highest_sales=np.max(sales)
lowest_sales=np.min(sales)
highest_month=np.argmax(sales)+1
lowest_month=np.argmin(sales)+1

In [37]:
print("total sales:",total_sales)

total sales: 263000


In [39]:
print("average sales:",average_sales)

average sales: 21916.666666666668


In [40]:
print("highest sales:",highest_sales)

highest sales: 32000


In [41]:
print("loowest sales:",lowest_sales)

loowest sales: 12000


In [42]:
print("highest sales month:",highest_month)

highest sales month: 12


In [43]:
print("lowest sales month:",lowest_month)

lowest sales month: 1
